{% set name = "types-pycurl" %}
{% set version = "7.44.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/types-pycurl-{{ version }}.tar.gz
  sha256: c125200ce9fc0a91e7f4679bd2c2ce6eedece68e83460833d0e150ccb5bbc6b1

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  commands:
    - test -f $SP_DIR/pycurl-stubs/__init__.pyi


about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for pycurl
  license: Apache-2.0 AND MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fhoehle
    - conda-forge/mypy
