{% set name = "types-pycurl" %}
{% set version = "7.44.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/types-pycurl-{{ version }}.tar.gz
  sha256: b68b1f7d695eea04134c61f3dec6ea5817fcabc165b2a58b394d58a0463e846f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  commands:
    - test -f $SP_DIR/pycurl-stubs/__init__.pyi


about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for pycurl
  license: Apache-2.0 AND MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fhoehle
    - conda-forge/mypy
