{% set name = "types-pycurl" %}
{% set version = "7.45.3.20240421" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/types-pycurl-{{ version }}.tar.gz
  sha256: 0d5b3b9243e3940e26b782c1cdc0b2438d244ee2e8dcde09cf523635a42ff406

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  commands:
    - test -f $SP_DIR/pycurl-stubs/__init__.pyi


about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for pycurl
  license: Apache-2.0 AND MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fhoehle
    - conda-forge/mypy
