{% set name = "types-pycurl" %}
{% set version = "7.45.2.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/types-pycurl-{{ version }}.tar.gz
  sha256: 93aceca81c083adf8048682d981133044aa1be279f921f403cba5846f396c0a6

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  commands:
    - test -f $SP_DIR/pycurl-stubs/__init__.pyi


about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for pycurl
  license: Apache-2.0 AND MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fhoehle
    - conda-forge/mypy
